"""PREPCHEM Reader"""

import xarray as xr
from .base import GriddedReader, register_reader

@register_reader("prepchem")
class PrepChemReader(GriddedReader):
    def open_dataset(self,
                     files,
                     dtype="f4",
                     res="C384",
                     tile=1,
                     **kwargs):
        """
        Reads binary data for FV3-CHEM input generated by prep_chem_sources.
        """
        # Expand paths
        from .drivers import FileUtility
        file_list = FileUtility.expand_paths(files)

        if len(file_list) == 1:
            return open_dataset_prepchem(file_list[0], dtype=dtype, res=res, tile=tile)
        else:
            # If multiple, maybe concat?
            # Original code returns DataArray.
            das = [open_dataset_prepchem(f, dtype=dtype, res=res, tile=tile) for f in file_list]
            # Assuming they are tiles? Or times?
            # If tiles, we might want to merge.
            # But let's just return list or concat if user wants?
            # For now, let's concat along a new dim 'file'?
            # Or just raise error if multiple.
            # But standard behavior is to combine.
            return xr.concat(das, dim="file")

# -----------------------------------------------------------------------------
# Helper functions ported from monetio/models/prepchem.py
# -----------------------------------------------------------------------------

def open_dataset_prepchem(fname, dtype="f4", res="C384", tile=1):
    try:
        import fv3grid as fg
        has_fv3grid = True
    except ImportError:
        has_fv3grid = False

    from pyresample.utils import wrap_longitudes
    from scipy.io import FortranFile

    w = FortranFile(fname, 'r')
    a = w.read_reals(dtype=dtype)
    w.close()

    r = int(res[1:])
    s = a.reshape((r, r), order="F")

    if has_fv3grid:
        grid = fg.get_fv3_grid(res=res, tile=tile)
        grid["longitude"] = wrap_longitudes(grid.longitude)
        name = fname.split(".bin")[0].split("/")[-1] # Simple name extraction
        grid[name] = (("x", "y"), s)
        return grid[name]
    else:
        print("Please install the fv3grid from https://github.com/bbakernoaa/fv3grid")
        print("to gain the full capability of this dataset")
        return xr.DataArray(s, dims=("x", "y"))
