"""PREPCHEM Reader"""

import xarray as xr

from .base import GriddedReader, register_reader
from .drivers import FileUtility


@register_reader("prepchem")
class PrepChemReader(GriddedReader):
    def open_dataset(self, files, dtype="f4", res="C384", tile=1, **kwargs):
        """
        Reads binary data for FV3-CHEM input generated by prep_chem_sources.
        """
        file_list = FileUtility.expand_paths(files)

        if len(file_list) == 1:
            return open_dataset_prepchem(file_list[0], dtype=dtype, res=res, tile=tile)
        else:
            das = [open_dataset_prepchem(f, dtype=dtype, res=res, tile=tile) for f in file_list]
            return xr.concat(das, dim="file")


# -----------------------------------------------------------------------------
# Helper functions ported from monetio/models/prepchem.py
# -----------------------------------------------------------------------------


def open_dataset_prepchem(fname, dtype="f4", res="C384", tile=1):
    try:
        import fv3grid as fg

        has_fv3grid = True
    except ImportError:
        has_fv3grid = False

    from pyresample.utils import wrap_longitudes
    from scipy.io import FortranFile

    fs = FileUtility.get_fs(fname)
    # FortranFile accepts a file object
    with fs.open(fname, "rb") as f_obj:
        # scipy.io.FortranFile needs a seekable file potentially?
        # fsspec files are usually seekable.
        # But FortranFile might expect a real file path if not passed an object.
        # It accepts "file-like object".

        w = FortranFile(f_obj, "r")
        a = w.read_reals(dtype=dtype)
        w.close()

    r = int(res[1:])
    s = a.reshape((r, r), order="F")

    if has_fv3grid:
        grid = fg.get_fv3_grid(res=res, tile=tile)
        grid["longitude"] = wrap_longitudes(grid.longitude)
        name = fname.split(".bin")[0].split("/")[-1]
        grid[name] = (("x", "y"), s)
        return grid[name]
    else:
        print("Please install the fv3grid from https://github.com/bbakernoaa/fv3grid")
        print("to gain the full capability of this dataset")
        return xr.DataArray(s, dims=("x", "y"))
