"""UFS-AQM variable specifications and diagnostic definitions."""

from .base import DiagnosticSpec

# Core species groups for cb6r3_ae6_aq mechanism
ACCUMULATION = [
    "aso4j",
    "ano3j",
    "anh4j",
    "anaj",
    "aclj",
    "aecj",
    "aothrj",
    "afej",
    "asij",
    "atij",
    "acaj",
    "amgj",
    "amnj",
    "aalj",
    "akj",
    "alvpo1j",
    "asvpo1j",
    "asvpo2j",
    "asvpo3j",
    "aivpo1j",
    "axyl1j",
    "axyl2j",
    "axyl3j",
    "atol1j",
    "atol2j",
    "atol3j",
    "abnz1j",
    "abnz2j",
    "abnz3j",
    "aiso1j",
    "aiso2j",
    "aiso3j",
    "atrp1j",
    "atrp2j",
    "asqtj",
    "aalk1j",
    "aalk2j",
    "apah1j",
    "apah2j",
    "apah3j",
    "aorgcj",
    "aolgbj",
    "aolgaj",
    "alvoo1j",
    "alvoo2j",
    "asvoo1j",
    "asvoo2j",
    "asvoo3j",
    "apcsoj",
]

AITKEN = [
    "aso4i",
    "ano3i",
    "anh4i",
    "anai",
    "acli",
    "aeci",
    "aothri",
    "alvpo1i",
    "asvpo1i",
    "asvpo2i",
    "alvoo1i",
    "alvoo2i",
    "asvoo1i",
    "asvoo2i",
]

COARSE = ["asoil", "acors", "aseacat", "aclk", "aso4k", "ano3k", "anh4k"]

# Diagnostic definitions
DIAGNOSTICS: dict[str, DiagnosticSpec] = {
    "PM25": DiagnosticSpec(
        variables=AITKEN + ACCUMULATION + COARSE,
        weights=[1.0] * (len(AITKEN) + len(ACCUMULATION)) + [0.2] * len(COARSE),
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5",
        name="PM2.5",
    ),
    "PM10": DiagnosticSpec(
        variables=AITKEN + ACCUMULATION + COARSE,
        weights=None,
        units=r"$\mu g m^{-3}$",
        long_name="PM10",
        name="PM10",
    ),
    "noy_gas": DiagnosticSpec(
        variables=[
            "no",
            "no2",
            "no3",
            "n2o5",
            "hono",
            "hno3",
            "pna",
            "cron",
            "clno2",
            "pan",
            "panx",
            "opan",
            "ntr1",
            "ntr2",
            "intr",
        ],
        weights=[1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        units="ppbV",
        long_name="NOy gas",
        name="noy_gas",
    ),
    "noy_aer": DiagnosticSpec(
        variables=["ano3i", "ano3j", "ano3k"],
        weights=None,
        units=r"$\mu g m^{-3}$",
        long_name="NOy aerosol",
        name="noy_aer",
    ),
    "nox": DiagnosticSpec(
        variables=["no", "no2"],
        weights=None,
        units="ppbV",
        long_name="NOx",
        name="nox",
    ),
    "pm25_cl": DiagnosticSpec(
        variables=["acli", "aclj", "aclk"],
        weights=[1, 1, 0.2],
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5 Chloride",
        name="pm25_cl",
    ),
    "pm25_ec": DiagnosticSpec(
        variables=["aeci", "aecj"],
        weights=None,
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5 Elemental Carbon",
        name="pm25_ec",
    ),
    "pm25_na": DiagnosticSpec(
        variables=["anai", "anaj", "aseacat", "asoil", "acors"],
        weights=[1, 1, 0.2 * 0.8373, 0.2 * 0.0626, 0.2 * 0.0023],
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5 Sodium",
        name="pm25_na",
    ),
    "pm25_ca": DiagnosticSpec(
        variables=["acaj", "aseacat", "asoil", "acors"],
        weights=[1, 0.2 * 0.0320, 0.2 * 0.0838, 0.2 * 0.0562],
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5 Calcium",
        name="pm25_ca",
    ),
    "pm25_nh4": DiagnosticSpec(
        variables=["anh4i", "anh4j", "anh4k"],
        weights=[1, 1, 0.2],
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5 Ammonium",
        name="pm25_nh4",
    ),
    "pm25_no3": DiagnosticSpec(
        variables=["ano3i", "ano3j", "ano3k"],
        weights=[1, 1, 0.2],
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5 Nitrate",
        name="pm25_no3",
    ),
    "pm25_so4": DiagnosticSpec(
        variables=["aso4i", "aso4j", "aso4k"],
        weights=[1, 1, 0.2],
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5 Sulfate",
        name="pm25_so4",
    ),
    "pm25_om": DiagnosticSpec(
        variables=ACCUMULATION[15:] + AITKEN[7:],
        weights=None,
        units=r"$\mu g m^{-3}$",
        long_name="PM2.5 Organic Matter",
        name="pm25_om",
    ),
}
