name: CI

on:
  push:
    branches:
      - stable
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: monetio-dev
          cache-environment: true
          condarc: |
            channels:
              - conda-forge
              - defaults
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install . --no-deps

      - name: Version info
        run: |
          conda info
          conda list

      - name: Run tests
        run: |
          pytest -v
